### ISSUE TITLE
Panic error when updating

### ISSUE THREAD

**Issue by MantisSTS** [MantisSTS/GoCloud#1]
There is a panic error when updating the cloud IPs. I believe this to be an issue with the Microsoft IP ranges but I need to investigate further.

```
[+] Updating cloud services IP ranges...(Program will exit after updates)
[+] Fetching IP ranges for AWS
[+] Fetching IP ranges for Google
[+] Fetching IP ranges for Azure
panic: invalid character '<' looking for beginning of value

goroutine 21 [running]:
main.(*CloudServices).UpdateCloudServices.func1({0x6ad450, 0x5}, {0x6c07e4?, 0x0?})
	/home/mantis/go/src/github.com/MantisSTS/GoClouds/main.go:251 +0x7f9
created by main.(*CloudServices).UpdateCloudServices
	/home/mantis/go/src/github.com/MantisSTS/GoClouds/main.go:149 +0x316

```

**Comment by MantisSTS** [comment]
Fixed this issue with  e9ac60c17ad804993dde9698b5855c526f3303ba
